apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-app-deployment
  labels:
    app: user-management-app
spec:
  replicas: 2 # Start with 2 replicas for high availability
  selector:
    matchLabels:
      app: user-management-app
  template:
    metadata:
      labels:
        app: user-management-app
    spec:
      containers:
      - name: user-management-app
        image: rahultiwari02/user-management-app:latest # IMPORTANT: Use your image path
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        env:
        - name: APPLICATION_SECURITY_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-management-secret
              key: APPLICATION_SECURITY_JWT_SECRET_KEY
        - name: APPLICATION_SECURITY_JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: user-management-config
              key: APPLICATION_SECURITY_JWT_EXPIRATION