apiVersion: v1
kind: Secret
metadata:
  name: user-management-secret
type: Opaque
data:
  APPLICATION_SECURITY_JWT_SECRET_KEY: c1RoaXNJc015TmV3U3VwZXJTdHJvbmdBbmRTZWN1cmVTZWNyZXRLZXlGb3JLdWJlcm5ldGVzMTIzIQ==
