apiVersion: v1
kind: Service
metadata:
  name: user-management-app-service
  labels:
    app: user-management-app
spec:
  type: LoadBalancer # Exposes the service externally. On local clusters, maps to localhost.
  selector:
    app: user-management-app
  ports:
    - protocol: TCP
      port: 8080        # The port the service will be available on
      targetPort: 8080  # The port the container is listening on